language: cpp
dist: focal

# Install LLVM
addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-13
      - llvm-13-dev
      - llvm-13-tools
      - clang-13
      - python3
      - python3-pip

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

compiler:
  - clang
  - gcc

# AFAIK, there's no other way of obtaining LLVM's lit other than via `pip
# install`
install:
  - pip3 install --user lit

script:
  # Build HelloWorld as a standalone project
  - cd $HOME/build/banach-space/llvm-tutor/HelloWorld
  - mkdir build && cd build
  - cmake -DLT_LLVM_INSTALL_DIR=/usr/lib/llvm-13/ -DCMAKE_BUILD_TYPE=$CONFIGURATION ../
  - make -j4
  # Build the top project and run tests
  - cd ../../
  - mkdir build
  - cd build
  - cmake -DLT_LLVM_INSTALL_DIR=/usr/lib/llvm-13/ -DCMAKE_BUILD_TYPE=$CONFIGURATION ../
  - make -j4
  - lit test/
